[package]
name = "oxilearn"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15"
rand = { version = "0.8", features = ["small_rng"] }
tch = { version = "0.16", features = ["download-libtorch"]}