[package]
name = "oxilearn"
version = "0.1.0"
edition = "2021"


[dependencies]
ndarray = "0.15"
tch = { version = "0.16" }
rand = { version="0.8", features = ["small_rng"] }
torch-sys = { version = "0.16" }
